// vue3_stundenplan/src/App.vue
<template>
  <main id="app" class="h-screen bg-gray-200">
    <div class="container p-10 mx-auto">
      <div>
        <SelectForm
          :value="jobId"
          @update="handelJobSelect"
          name="Beruf"
          :values="jobs"
        />
      </div>
      <div v-show="jobId">
        <div class="hidden sm:block">
          <div class="py-5">
            <hr class="h-px text-gray-500" />
          </div>
        </div>
        <SelectForm
          name="Klasse"
          :value="classId"
          @update="handelClassSelect"
          :values="classes"
        />
      </div>
      <div v-show="classId">
        <div class="hidden sm:block">
          <div class="py-5">
            <hr class="h-px text-gray-500" />
          </div>
        </div>
        <Pagination />
        <transition
          mode="out-in"
          enter-from-class="opacity-0"
          enter-active-class="duration-500 ease-out"
          enter-to-class="opacity-100"
          leave-from-class="opacity-100"
          leave-active-class="duration-300 ease-in"
          leave-to-class="opacity-0"
        >
          <LectureTable
            class="transition-all"
            :key="`${classId}-${weekString}`"
            :lectures="lectures"
          />
        </transition>
      </div>
    </div>

    <Portal target="#portalTaget">
      <div v-if="error" class="absolute inset-x-0 top-0 max-w-md m-4 mx-auto">
        <p
          class="px-4 py-2 text-red-800 bg-red-300 border border-red-700 rounded-sm"
        >
          {{ error }}
        </p>
      </div>
    </Portal>
  </main>
</template>

<script>
import { ref, onErrorCaptured } from 'vue'
import SelectForm from './components/SelectForm'
import LectureTable from './components/LectureTable'
import Pagination from './components/Pagination'
import { usePersistedState, useJobs, useLectures, useClasses } from './hooks'
import { useWeekCalculator } from './WeekCalculator'

export default {
  name: 'app',
  components: {
    LectureTable,
    SelectForm,
    Pagination,
  },
  setup() {
    let jobId = usePersistedState('jobID', true)
    let classId = usePersistedState('classID')
    let { weekString } = useWeekCalculator()

    let jobs = useJobs()

    let classes = useClasses(jobId)

    let lectures = useLectures(classId, weekString)

    const handelJobSelect = val => {
      classId.value = ''
      jobId.value = val
    }

    const handelClassSelect = val => {
      classId.value = val
    }

    let error = ref(null)

    onErrorCaptured(e => {
      console.log(e)
      error.value = 'Uh oh. Something went wrong!'
      return true
    })

    return {
      jobId,
      jobs,
      classId,
      classes,
      lectures,
      weekString,
      handelJobSelect,
      handelClassSelect,
      error,
    }
  },
}
</script>

<style>
@tailwind base;
@tailwind components;
@tailwind utilities;
</style>

// react_stundenplan/src/App.js
import React, { Fragment } from 'react'
import Spacer from './components/Spacer'
import SelectForm from './components/SelectForm'
import {
  useJobs,
  useSchoolClass,
  useDateCalc,
  useSchdual,
  usePersistedState,
} from './hooks'
import { Transition } from './components/Transition'
import LectureTable from './components/LectureTable'
import Navigation from './components/Navigation'

function App() {
  let [selectedJob, setSelectedJob] = usePersistedState('jobId', true)
  let [selectedClass, setSelectedClass] = usePersistedState('classId')

  let { getWeekString } = useDateCalc()

  let { jobs: berufe, loading: loadingJobs } = useJobs()
  let { schoolClasses, loading: loadingClass } = useSchoolClass(selectedJob)
  let { schdual, loading: loadingSchdual } = useSchdual(
    selectedClass,
    getWeekString
  )

  let handelSelect = event => {
    setSelectedClass('')
    setSelectedJob(event.target.value)
  }

  let handelClassSelect = event => {
    setSelectedClass(event.target.value)
  }

  return (
    <main className="h-screen bg-gray-200">
      <div className="container p-10 mx-auto">
        <Transition
          enterFrom="opacity-0"
          enter="duration-300 ease-out"
          enterTo="opacity-100"
          leaveFrom="opacity-100"
          leave="duration-200 ease-in"
          leaveTo="opacity-0"
          show={!loadingJobs}
        >
          <SelectForm
            value={selectedJob}
            name="Beruf"
            onChange={handelSelect}
            options={berufe}
          />
        </Transition>

        <Spacer />
        {selectedJob && (
          <Transition
            enterFrom="opacity-0"
            enter="duration-300 ease-out"
            enterTo="opacity-100"
            leaveFrom="opacity-100"
            leave="duration-200 ease-in"
            leaveTo="opacity-0"
            show={!loadingClass}
          >
            <SelectForm
              value={selectedClass}
              key={selectedJob}
              name="Klasse"
              onChange={handelClassSelect}
              options={schoolClasses}
            />
          </Transition>
        )}

        {selectedClass && (
          <Fragment>
            <Spacer />
            <Transition
              enterFrom="opacity-0"
              enter="duration-300 ease-out"
              enterTo="opacity-100"
              leaveFrom="opacity-100"
              leave="duration-200 ease-in"
              leaveTo="opacity-0"
              show={!!selectedClass}
            >
              <Navigation />
            </Transition>
            <Transition
              enterFrom="opacity-0"
              enter="duration-300 ease-out"
              enterTo="opacity-100"
              leaveFrom="opacity-100"
              leave="duration-200 ease-in"
              leaveTo="opacity-0"
              show={!loadingSchdual}
            >
              <LectureTable schdual={schdual} />
            </Transition>
          </Fragment>
        )}
      </div>
    </main>
  )
}

export default App
