// vue3_stundenplan/src/components/LectureTable.vue
<template>
  <table class="w-full bg-gray-100 rounded shadow ">
    <thead class="h-12 border-b-2 rounded-t">
      <tr>
        <th class="px-4 text-left">Wochentag/Datum</th>
        <th class="px-2">Von</th>
        <th class="px-2">Bis</th>
        <th class="px-4 text-left">Fach</th>
        <th class="px-4 text-left">Lehrer</th>
        <th class="px-4 text-left">Zimmer</th>
        <th class="px-4 text-left">Bemerkung</th>
      </tr>
    </thead>
    <tbody>
      <tr
        class="h-12 text-sm border-b border-gray-200"
        v-for="lecture in lectures"
        :key="lecture.tafel_id"
      >
        <td class="px-4">
          {{ toHumanReadableDate(lecture.tafel_datum) }}
        </td>
        <td class="px-2 text-center">
          {{ toShortTime(lecture.tafel_von) }}
        </td>
        <td class="px-2 text-center">
          {{ toShortTime(lecture.tafel_bis) }}
        </td>
        <td class="px-4">
          {{ lecture.tafel_longfach }}
        </td>
        <td class="px-4">
          {{ lecture.tafel_lehrer }}
        </td>
        <td class="px-4">
          {{ lecture.tafel_raum }}
        </td>
        <td class="px-4">
          {{ lecture.tafel_kommentar }}
        </td>
      </tr>
    </tbody>
  </table>
</template>

<script>
import { ref } from 'vue'
import { getZeitTafel } from '../api'
export default {
  props: {
    klasse: String,
  },
  async setup(props) {
    let lectures = ref([])
    lectures.value = await getZeitTafel(props.klasse)
    const toHumanReadableDate = date =>
      new Date(date).toLocaleDateString('de-CH', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })

    const toShortTime = time => time.slice(0, 5)

    return {
      lectures,
      toHumanReadableDate,
      toShortTime,
    }
  },
}
</script>

// react_stundenplan/src/components/LectureTable.js
import React from 'react'

export function LectureRow({ lecture }) {
  const toHumanReadableDate = date =>
    new Date(date).toLocaleDateString('de-CH', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })

  const toShortTime = time => time.slice(0, 5)

  return (
    <tr className="h-12 text-sm border-b border-gray-200">
      <td className="px-4">{toHumanReadableDate(lecture.tafel_datum)}</td>
      <td className="px-2 text-center">{toShortTime(lecture.tafel_von)}</td>
      <td className="px-2 text-center">{toShortTime(lecture.tafel_bis)}</td>
      <td className="px-4">{lecture.tafel_longfach}</td>
      <td className="px-4">{lecture.tafel_lehrer}</td>
      <td className="px-4">{lecture.tafel_raum}</td>
      <td className="px-4">{lecture.tafel_kommentar}</td>
    </tr>
  )
}

export function LectureTableLoading() {
  return (
    <table className="w-full bg-gray-100 rounded shadow ">
      <thead className="h-12 border-b-2 rounded-t">
        <tr>
          <th className="px-4 text-left">Wochentag/Datum</th>
          <th className="px-2">Von</th>
          <th className="px-2">Bis</th>
          <th className="px-4 text-left">Fach</th>
          <th className="px-4 text-left">Lehrer</th>
          <th className="px-4 text-left">Zimmer</th>
          <th className="px-4 text-left">Bemerkung</th>
        </tr>
      </thead>
      <tbody>
        <tr className="h-12 text-sm border-b border-gray-200">
          <td className="px-4">Loading...</td>
          <td className="px-2 text-center">Loading...</td>
          <td className="px-2 text-center">Loading...</td>
          <td className="px-4">Loading...</td>
          <td className="px-4">Loading...</td>
          <td className="px-4">Loading...</td>
          <td className="px-4">Loading...</td>
        </tr>
      </tbody>
    </table>
  )
}

export function LectureTable({ schdual }) {
  return (
    <table className="w-full bg-gray-100 rounded shadow">
      <thead className="border-4 border-transparent rounded-t">
        <tr className="">
          <th className="px-4 text-left">Wochentag/Datum</th>
          <th className="px-2">Von</th>
          <th className="px-2">Bis</th>
          <th className="px-4 text-left">Fach</th>
          <th className="px-4 text-left">Lehrer</th>
          <th className="px-4 text-left">Zimmer</th>
          <th className="px-4 text-left">Bemerkung</th>
        </tr>
      </thead>
      <tbody>
        {schdual.map((lecture, index) => (
          <LectureRow lecture={lecture} key={index} />
        ))}
      </tbody>
    </table>
  )
}

export default LectureTable
