// vue3_stundenplan/src/components/SelectForm.vue
<template>
  <label class="block">
    <span class="font-semibold">{{ $props.name }}</span>
    <select
      class="block w-full shadow form-select"
      @input="e => $emit('update', e.target.value)"
    >
      <option disabled :selected="$props.value === ''">
        {{ $props.name }} wählen.
      </option>
      <option
        v-for="value in $props.values"
        :selected="$props.value === value[`${$props.name.toLowerCase()}_id`]"
        :value="value[`${$props.name.toLowerCase()}_id`]"
        :key="value[`${$props.name.toLowerCase()}_id`]"
      >
        {{ value[`${$props.name.toLowerCase()}_name`] }}
      </option>
    </select>
  </label>
</template>

// react_stundenplan/src/components/SelectForm.js
import React from 'react'

function SelectForm({ name, value, onChange, options }) {
  return (
    <label className="block">
      <span className="font-semibold">{name}</span>
      <select
        className="block w-full shadow form-select"
        value={value}
        onChange={onChange}
      >
        <option value="" hidden disabled>
          {name} wählen
        </option>
        {options.map((value, index) => (
          <option key={index} value={value[`${name.toLowerCase()}_id`]}>
            {value[`${name.toLowerCase()}_name`]}
          </option>
        ))}
      </select>
    </label>
  )
}

export default SelectForm
